import Uint8ArrayList from "../code/ArrayList";

test("array list", () => {
  const list = new Uint8ArrayList(10);
  expect(list.print()).toBe("[]");
  expect(list.getLength()).toBe(0);
  expect(list.pop()).toBe(undefined);
  expect(list.push(3)).toBe(1);
  expect(list.getLength()).toBe(1);
  expect(list.print()).toBe("[3]");
  expect(list.get(0)).toBe(3);
  expect(() => list.get(1)).toThrow("Out of bounds");
  expect(list.push(9)).toBe(2);
  expect(list.push(7)).toBe(3);
  expect(list.push(5)).toBe(4);
  expect(list.getLength()).toBe(4);
  expect(list.pop()).toBe(5);
  expect(list.getLength()).toBe(3);
  expect(list.print()).toBe("[3, 9, 7]");
  expect(list.unshift(9)).toBe(4);
  expect(list.unshift(7)).toBe(5);
  expect(list.print()).toBe("[7, 9, 3, 9, 7]");
  expect(list.push(1)).toBe(6);
  expect(list.push(2)).toBe(7);
  expect(list.push(3)).toBe(8);
  expect(list.push(4)).toBe(9);
  expect(list.push(5)).toBe(10);
  expect(() => list.push(6)).toThrow("Insufficient memory");
  expect(list.print()).toBe("[7, 9, 3, 9, 7, 1, 2, 3, 4, 5]");
  expect(list.shift()).toBe(7);
  expect(list.shift()).toBe(9);
  expect(list.get(4)).toBe(2);
  expect(list.shift()).toBe(3);
  expect(list.shift()).toBe(9);
  expect(list.getLength()).toBe(6);
  expect(list.shift()).toBe(7);
  expect(list.shift()).toBe(1);
  expect(list.shift()).toBe(2);
  expect(list.shift()).toBe(3);
  expect(list.shift()).toBe(4);
  expect(list.shift()).toBe(5);
  expect(list.shift()).toBe(undefined);
});
